name: 'cloudflare-cache-purge-action'
description: 'A custom GitHub Action to purge CloudFlare cache for a specified zone'
author: 'https://github.com/xparty-ent'

# Define your inputs here.
inputs:
  CLOUDFLARE_ZONE:
    description: 'The CloudFlare Zone used to purge the cache'
    required: true
    default: ''
  CLOUDFLARE_TOKEN:
    description: 'The CloudFlare API Token used to authenticate requests'
    required: true
    default: ''

runs:
  using: node20
  main: dist/index.js
